print ("Enter the valuse of the quadratic equation.A,B&C", end=' ')
a=int(input())
b=int(input())
c=int(input())
d=int((b**2))
e=int(4*a*c)
f=int(d-e)
g=int((f**0.5))
h=int(-b+g)
i=int(-b-g)
j=int(h/(a*2))
k=int(i/(a*2))
print (f"the roots are{j}&{k}.")